framework:
    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        prefix_seed: jtwc/mlm_redis

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.app
            jtwc_mlm.entities:
                adapter: cache.app
