security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        users:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            pattern: ^/
            provider: users
            logout:
                path: jtwc_app_logout
                target: jtwc_app_login
            custom_authenticator: App\Security\LoginFormAuthenticator
            user_checker: App\Security\UserChecker
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                token_provider: 'Symfony\Bridge\Doctrine\Security\RememberMe\DoctrineTokenProvider'

    role_hierarchy:
        ROLE_JTWC_ADMIN:
            - ROLE_JTWC_USER_SECRET
            - ROLE_JTWC_USER
        ROLE_JTWC_USER_SECRET : ROLE_JTWC_USER

    access_control:
         - { path: ^/login$, roles: PUBLIC_ACCESS }
         - { path: ^/admin/order-product/notify$, roles: PUBLIC_ACCESS }
         - { path: ^/admin/order-product/validate$, roles: PUBLIC_ACCESS }
         - { path: ^/admin/payment-product/success$, roles: PUBLIC_ACCESS }
         - { path: ^/admin/payment-product/fail$, roles: PUBLIC_ACCESS }
         - { path: ^/admin/payment-subscription/success$, roles: PUBLIC_ACCESS }
         - { path: ^/admin/payment-subscription/fail$, roles: PUBLIC_ACCESS }
         - { path: ^/admin/order-membership-subscription/notify$, roles: PUBLIC_ACCESS }
         - { path: ^/admin/order-membership/validate$, roles: PUBLIC_ACCESS }
         - { path: ^/, roles: ROLE_JTWC_USER }
