security_controllers:
    resource: ../../src/Controller/
    type: attribute
    defaults:
        schemes: [https]

back_controllers:
    resource: ../../src/Controller/Back/WebController/
    type: attribute
    prefix: /admin
    defaults:
        schemes: [https]
